name: Build On Tag
on: [push]
jobs:
  Build-And-Pusblish:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Build OSX runtime
        run: |
          ${{ github.workspace }}/scripts/build-runtime.ps1 osx

      - name: List build artifacts
        run: |
          ls ${{ github.workspace }}/runtimes/*

      - run: echo "🍏 This job's status is ${{ job.status }}."