name: Build New Version
on:
  push:
    tags:
      - 'v*'

jobs:
  create_release:
    runs-on: ubuntu-20.04
    outputs:
      release_id: ${{ steps.create_release.outputs.id }}
    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

  build_and_publish:
    needs: [create_release]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target_os: osx
          - os: windows-latest
            target_os: win

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Prepare Builder
        shell: pwsh
        run: |
          ${{ github.workspace }}/scripts/prepare-builder.ps1 ${{ matrix.target_os }}
          

      - name: Build Runtime
        shell: pwsh
        run: |
          ${{ github.workspace }}/scripts/build-runtime.ps1 ${{ matrix.target_os }}

      - name: Upload Release Archive
        id: upload-release-assets
        uses: dwenegar/upload-release-assets@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{needs.create_release.outputs.release_id}}
          assets_path: ${{ github.workspace }}/runtimes
