name: Build On Tag
on: [push]
jobs:
  Build-And-Publish:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Build OSX runtime
        run: |
          ${{ github.workspace }}/scripts/build-runtime.ps1 osx

      - name: Publish built artifacts
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          title: "Test Build"
          files: |
            ${{ github.workspace }}/runtimes/*.zip
