name: Build On Tag
on:
  push:
    branches:
      - '*'

jobs:
  create_release:
    runs-on: ubuntu-20.04
    outputs:
      release_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

  build_on_os:
    needs: [create_release]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Prepare Builder on Windows
        if: matrix.os == 'ubuntu-windows'
        shell: pwsh
        run: |
          choco install -y nodejs zip curl

      - name: Prepare Builder on MacOSX
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get install -y npm zip curl

      - name: Build Windows runtime
        if: matrix.os == 'ubuntu-windows'
        shell: pwsh
        run: |
          ${{ github.workspace }}/scripts/build-runtime.ps1 win

      - name: Build OSX runtime
        if: matrix.os == 'ubuntu-latest'
        run: |
          ${{ github.workspace }}/scripts/build-runtime.ps1 osx  

      - name: Upload Release Archive
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{needs.create_release.outputs.release_url}}
          asset_path: ${{ github.workspace }}/runtimes/games.cm.cme.runtime.*.*
          asset_name: games.cm.cme.runtime.*.*
