name: Build On Tag
on:
  push:
    tags:
      - "v*"

jobs:
  Build-And-Publish-Windows:
    runs-on: windows-2022
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Prepare Builder
        shell: pwsh
        run: |
          choco install -y nodejs zip curl

      - name: Build Windows runtime
        shell: pwsh
        run: |
          ${{ github.workspace }}/scripts/build-runtime.ps1 win

      - name: Publish built artifacts
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          files: |
            ${{ github.workspace }}/runtimes/*.zip
            ${{ github.workspace }}/runtimes/*.sha256

  Build-And-Publish-MacOSX:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Prepare Builder
        run: |
          sudo apt-get install -y npm zip curl

      - name: Build OSX runtime
        run: |
          ${{ github.workspace }}/scripts/build-runtime.ps1 osx

      - name: Publish built artifacts
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          files: |
            ${{ github.workspace }}/runtimes/*.zip
            ${{ github.workspace }}/runtimes/*.sha256
